import {
  DetailedLead,
  MinimalLead,
  NewDetailedLead,
  NewMinimalLead,
} from "@/types";

export const leads: MinimalLead[] = [
  {
    lead_id: "987654321",
    lead_name: "John Duo",
    current_state: {
      label: {
        en: "Application Created",
        ar: "تم إنشاء الطلب",
      },
      color: "#FFA500",
    },
    actor: "Dealer",
    created_date: "2023-12-31T08:00:00Z",
    last_updated_at: "2023-12-31T08:05:00Z",
    iqama_id: "123456789012",
    phone_number: "+1234567890",
    email: "john.duo@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "123456789",
    lead_name: "Alice Smith",
    current_state: {
      label: {
        en: "Bank Decision",
        ar: "قرار البنك",
      },
      color: "#FFA500",
    },
    actor: "Bank",
    created_date: "2023-12-30T09:00:00Z",
    last_updated_at: "2023-12-31T09:30:00Z",
    iqama_id: "987654321098",
    phone_number: "+19876543210",
    email: "alice.smith@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "111111111",
    lead_name: "Mohammed Ahmed",
    current_state: {
      label: {
        en: "Customer Upload Docs",
        ar: "تحميل مستندات العميل",
      },
      color: "#FFA500",
    },
    actor: "Customer",
    created_date: "2023-12-30T10:00:00Z",
    last_updated_at: "2023-12-31T10:30:00Z",
    iqama_id: "555555555555",
    phone_number: "+112233445566",
    email: "mohammed.ahmed@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "222222222",
    lead_name: "Fatima Abdulaziz",
    current_state: {
      label: {
        en: "Bank Decision",
        ar: "قرار البنك",
      },
      color: "#FFA500",
    },
    actor: "Bank",
    created_date: "2023-12-29T12:00:00Z",
    last_updated_at: "2023-12-31T11:45:00Z",
    iqama_id: "444444444444",
    phone_number: "+1231231234",
    email: "fatima.abdulaziz@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "333333333",
    lead_name: "Ahmed Hassan",
    current_state: {
      label: {
        en: "Customer Upload Docs",
        ar: "تحميل مستندات العميل",
      },
      color: "#FFA500",
    },
    actor: "Customer",
    created_date: "2023-12-28T15:00:00Z",
    last_updated_at: "2023-12-31T13:20:00Z",
    iqama_id: "777777777777",
    phone_number: "+9876543210",
    email: "ahmed.hassan@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "444444444",
    lead_name: "Sara Khalid",
    current_state: {
      label: {
        en: "Bank Decision",
        ar: "قرار البنك",
      },
      color: "#FFA500",
    },
    actor: "Bank",
    created_date: "2023-12-27T14:00:00Z",
    last_updated_at: "2023-12-31T14:55:00Z",
    iqama_id: "666666666666",
    phone_number: "+1122334455",
    email: "sara.khalid@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "555555555",
    lead_name: "Ali Mohammed",
    current_state: {
      label: {
        en: "Application Created",
        ar: "تم إنشاء الطلب",
      },
      color: "#FFA500",
    },
    actor: "Dealer",
    created_date: "2023-12-26T11:00:00Z",
    last_updated_at: "2023-12-31T15:30:00Z",
    iqama_id: "999999999999",
    phone_number: "+1112233445",
    email: "ali.mohammed@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "666666666",
    lead_name: "Aisha Omar",
    current_state: {
      label: {
        en: "Customer Upload Docs",
        ar: "تحميل مستندات العميل",
      },
      color: "#FFA500",
    },
    actor: "Customer",
    created_date: "2023-12-25T16:00:00Z",
    last_updated_at: "2023-12-31T16:40:00Z",
    iqama_id: "888888888888",
    phone_number: "+1122334455",
    email: "aisha.omar@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "777777777",
    lead_name: "Omar Khalid",
    current_state: {
      label: {
        en: "Bank Decision",
        ar: "قرار البنك",
      },
      color: "#FFA500",
    },
    actor: "Bank",
    created_date: "2023-12-24T17:00:00Z",
    last_updated_at: "2023-12-31T17:50:00Z",
    iqama_id: "111111111111",
    phone_number: "+1122334455",
    email: "omar.khalid@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "888888888",
    lead_name: "Reem Abdulaziz",
    current_state: {
      label: {
        en: "Application Created",
        ar: "تم إنشاء الطلب",
      },
      color: "#FFA500",
    },
    actor: "Dealer",
    created_date: "2023-12-23T18:00:00Z",
    last_updated_at: "2023-12-31T18:35:00Z",
    iqama_id: "222222222222",
    phone_number: "+1122334455",
    email: "reem.abdulaziz@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "999999999",
    lead_name: "Youssef Hassan",
    current_state: {
      label: {
        en: "Customer Upload Docs",
        ar: "تحميل مستندات العميل",
      },
      color: "#FFA500",
    },
    actor: "Customer",
    created_date: "2023-12-22T19:00:00Z",
    last_updated_at: "2023-12-31T19:25:00Z",
    iqama_id: "333333333333",
    phone_number: "+1122334455",
    email: "youssef.hassan@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "1010101010",
    lead_name: "Layla Ibrahim",
    current_state: {
      label: {
        en: "Bank Decision",
        ar: "قرار البنك",
      },
      color: "#FFA500",
    },
    actor: "Bank",
    created_date: "2023-12-21T20:00:00Z",
    last_updated_at: "2023-12-31T20:15:00Z",
    iqama_id: "444444444444",
    phone_number: "+1122334455",
    email: "layla.ibrahim@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "1111111111",
    lead_name: "Yara Khalid",
    current_state: {
      label: {
        en: "Application Created",
        ar: "تم إنشاء الطلب",
      },
      color: "#FFA500",
    },
    actor: "Dealer",
    created_date: "2023-12-20T21:00:00Z",
    last_updated_at: "2023-12-31T21:45:00Z",
    iqama_id: "555555555555",
    phone_number: "+1122334455",
    email: "yara.khalid@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "1212121212",
    lead_name: "Ahmed Abdullah",
    current_state: {
      label: {
        en: "Customer Upload Docs",
        ar: "تحميل مستندات العميل",
      },
      color: "#FFA500",
    },
    actor: "Customer",
    created_date: "2023-12-19T22:00:00Z",
    last_updated_at: "2023-12-31T22:35:00Z",
    iqama_id: "666666666666",
    phone_number: "+1122334455",
    email: "ahmed.abdullah@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
  {
    lead_id: "1313131313",
    lead_name: "Noor Mohammed",
    current_state: {
      label: {
        en: "Bank Decision",
        ar: "قرار البنك",
      },
      color: "#FFA500",
    },
    actor: "Bank",
    created_date: "2023-12-18T23:00:00Z",
    last_updated_at: "2023-12-31T23:10:00Z",
    iqama_id: "777777777777",
    phone_number: "+1122334455",
    email: "noor.mohammed@example.com",
    status: {
      en: "Active",
      ar: "نشط",
    },
  },
];

export const Leads: DetailedLead[] = [
  {
    lead_id: "123456789",
    customer_name: {
      value: "John Doe",
      labels: {
        en: "Customer Name",
        ar: "اسم الزبون",
      },
    },
    phone_number: "+1234567890",
    email: "john.doe@example.com",
    iqama_id: "123456789012",
    profession: {
      value: "Salaried",
      labels: {
        en: "Profession",
        ar: "المهنة",
      },
    },
    monthly_income: {
      value: 5000,
      labels: {
        en: "Monthly Income",
        ar: "الدخل الشهري",
      },
    },
    other_loans: {
      value: false,
      labels: {
        en: "Other Loans",
        ar: "القروض الأخرى",
      },
    },
    vehicle_details: {
      registration_number: "ABC123",
      brand: {
        value: "Toyota",
        labels: {
          en: "Brand",
          ar: "العلامة التجارية",
        },
      },
      variant: {
        value: "Camry",
        labels: {
          en: "Variant",
          ar: "المتغير",
        },
      },
      color: {
        value: "White",
        labels: {
          en: "Color",
          ar: "اللون",
        },
      },
      addons: [
        {
          value: "Sunroof",
          labels: {
            en: "Add-Ons",
            ar: "الإضافات",
          },
        },
        {
          value: "Leather Seats",
          labels: {
            en: "Add-Ons",
            ar: "الإضافات",
          },
        },
      ],
    },
    bank_decision: {
      decision: {
        value: "Approved",
        labels: {
          en: "Decision",
          ar: "القرار",
        },
      },
      approval_amount: {
        value: 25000,
        labels: {
          en: "Approval Amount",
          ar: "مبلغ الموافقة",
        },
      },
      interest_rate: {
        value: 3.5,
        labels: {
          en: "Interest Rate",
          ar: "سعر الفائدة",
        },
      },
    },
    contract_signed: {
      value: true,
      labels: {
        en: "Contract Signed",
        ar: "العقد موقع",
      },
    },
    booking_fee_paid: {
      value: true,
      labels: {
        en: "Booking Fee Paid",
        ar: "دفع رسوم الحجز",
      },
    },
    vehicle_received: {
      value: true,
      labels: {
        en: "Vehicle Received",
        ar: "تم استلام المركبة",
      },
    },
    attached_documents: [
      {
        name: {
          en: "Salary Certificate",
          ar: "شهادة الراتب",
        },
        file_url: "https://example.com/salary_certificate.pdf",
      },
      {
        name: {
          en: "Iqama Photo",
          ar: "صورة الإقامة",
        },
        file_url: "https://example.com/iqama_photo.jpg",
      },
      {
        name: {
          en: "Passport-sized Photo",
          ar: "صورة جواز السفر بحجم الجيب",
        },
        file_url: "https://example.com/passport_photo.jpg",
      },
    ],
    current_state: {
      label: {
        en: "Vehicle Received",
        ar: "تم استلام المركبة",
      },
      color: "#008000",
    },
    state_history: [
      {
        state: {
          en: "Application Created",
          ar: "تم إنشاء الطلب",
        },
        timestamp: "2023-12-25T09:00:00Z",
      },
      {
        state: {
          en: "Bank Decision",
          ar: "قرار البنك",
        },
        timestamp: "2023-12-26T09:30:00Z",
      },
      {
        state: {
          en: "Contract Signed",
          ar: "تم توقيع العقد",
        },
        timestamp: "2023-12-27T10:00:00Z",
      },
      {
        state: {
          en: "Booking Fee Paid",
          ar: "تم دفع رسوم الحجز",
        },
        timestamp: "2023-12-28T11:00:00Z",
      },
      {
        state: {
          en: "Vehicle Received",
          ar: "تم استلام المركبة",
        },
        timestamp: "2023-12-29T12:00:00Z",
      },
    ],
  },
  {
    lead_id: "987654321",
    customer_name: {
      value: "Alice Smith",
      labels: {
        en: "Customer Name",
        ar: "اسم الزبون",
      },
    },
    phone_number: "+19876543210",
    email: "alice.smith@example.com",
    iqama_id: "987654321098",
    profession: {
      value: "Self-Employed",
      labels: {
        en: "Profession",
        ar: "المهنة",
      },
    },
    monthly_income: {
      value: 6000,
      labels: {
        en: "Monthly Income",
        ar: "الدخل الشهري",
      },
    },
    other_loans: {
      value: true,
      labels: {
        en: "Other Loans",
        ar: "القروض الأخرى",
      },
    },
    vehicle_details: {
      registration_number: "XYZ789",
      brand: {
        value: "Honda",
        labels: {
          en: "Brand",
          ar: "العلامة التجارية",
        },
      },
      variant: {
        value: "Civic",
        labels: {
          en: "Variant",
          ar: "المتغير",
        },
      },
      color: {
        value: "Red",
        labels: {
          en: "Color",
          ar: "اللون",
        },
      },
      addons: [
        {
          value: "Navigation System",
          labels: {
            en: "Add-Ons",
            ar: "الإضافات",
          },
        },
        {
          value: "Premium Audio System",
          labels: {
            en: "Add-Ons",
            ar: "الإضافات",
          },
        },
      ],
    },
    bank_decision: {
      decision: {
        value: "Pending",
        labels: {
          en: "Decision",
          ar: "القرار",
        },
      },
      approval_amount: {
        value: null,
        labels: {
          en: "Approval Amount",
          ar: "مبلغ الموافقة",
        },
      },
      interest_rate: {
        value: null,
        labels: {
          en: "Interest Rate",
          ar: "سعر الفائدة",
        },
      },
    },
    contract_signed: {
      value: false,
      labels: {
        en: "Contract Signed",
        ar: "العقد موقع",
      },
    },
    booking_fee_paid: {
      value: false,
      labels: {
        en: "Booking Fee Paid",
        ar: "دفع رسوم الحجز",
      },
    },
    vehicle_received: {
      value: false,
      labels: {
        en: "Vehicle Received",
        ar: "تم استلام المركبة",
      },
    },
    attached_documents: [
      {
        name: {
          en: "Salary Certificate",
          ar: "شهادة الراتب",
        },
        file_url: "https://example.com/alice_smith_salary_certificate.pdf",
      },
      {
        name: {
          en: "Iqama Photo",
          ar: "صورة الإقامة",
        },
        file_url: "https://example.com/alice_smith_iqama_photo.jpg",
      },
    ],
    current_state: {
      label: {
        en: "Bank Decision",
        ar: "قرار البنك",
      },
      color: "#FFA500",
    },
    state_history: [
      {
        state: {
          en: "Application Created",
          ar: "تم إنشاء الطلب",
        },
        timestamp: "2023-12-30T09:00:00Z",
      },
      {
        state: {
          en: "Bank Decision",
          ar: "قرار البنك",
        },
        timestamp: "2023-12-31T09:30:00Z",
      },
    ],
  },
];

export const newLeads: NewMinimalLead[] = [
  {
    application_id: {
      application_id: "987654321",
      lead_name: "John Duo",
      lead_ID: "lead_234565432",
      current_state: {
        label: {
          en: "Application Created",
          ar: "تم إنشاء الطلب",
        },
        color: "#FFA500",
      },
      current_actor: "Dealer",
      created_date: "2023-12-31T08:00:00Z",
      last_updated_at: "2023-12-31T08:05:00Z",
      iqama_id: "123456789012",
      driving_license_number: "MH12 20211234567",
      phone_number: "+1234567890",
      email: "john.duo@example.com",
      is_verified: "yes",
      status: "active",
      car_details: {
        brand: "KIA",
        model: "K8",
        variant: "KIA K8 2023 3.5L GDI LX",
        price: {
          actual: "85,000",
          discount: "2500",
          final_price: "82500",
        },
        car_image: "https://www.img.com/234567654321",
        color: { en: "Carpet Red", ar: "سجادة باللون الأحمر" },
      },
      lessor_details: {
        lessor_name: {
          en: "Demo Bank",
          ar: "بنك تجريبي",
        },
        recommended: "no",
        lessor_logo: "https://www.img.com/234567897654",
        lessor_ID: "LESSOR_87654323456",
        lessor_type: "bank",
        lessor_contact: {
          name: { en: "Mashal", ar: "مشعل" },
          phone: "+97199887766554",
          email: "lessoremail@demolessor.com",
        },
      },
      progress_measure: "70",
      is_draft: "yes",
      dealer_details: {
        dealer_id: "dealer_65432345678",
        dealer_name: {
          en: "National Motor Distributors",
          ar: "الموزعون الوطنيون للمحركات",
        },
        dealer_logo: "https://www.img.com/234567897654",
        dealer_contact: {
          name: { en: "Yazan", ar: "يزن" },
          phone: "+97199887766554",
          email: "dealeremail@demodealer.com",
        },
      },
      assigned_to_dealer_agent: "dealer_AGENTID_765432345",
      assigned_to_lessor_agent: "lessor_AGENTID_765432345",
    },
  },
  {
    application_id: {
      application_id: "123456789",
      lead_name: "Alice Smith",
      lead_ID: "lead_234565432",
      current_state: {
        label: {
          en: "Bank Decision",
          ar: "قرار البنك",
        },
        color: "#FFA500",
      },
      current_actor: "Bank",
      created_date: "2023-12-30T09:00:00Z",
      last_updated_at: "2023-12-31T09:30:00Z",
      iqama_id: "987654321098",
      driving_license_number: "MH12 20211234567",
      phone_number: "+19876543210",
      email: "alicesmith123@gmail.com",
      is_verified: "yes",
      status: "active",
      car_details: {
        brand: "KIA",
        model: "K8",
        variant: "KIA K8 2023 3.5L GDI LX",
        price: {
          actual: "85,000",
          discount: "2500",
          final_price: "82500",
        },
        car_image: "https://www.img.com/234567654321",
        color: { en: "Carpet Red", ar: "سجادة باللون الأحمر" },
      },
      lessor_details: {
        lessor_name: {
          en: "Demo Bank",
          ar: "بنك تجريبي",
        },
        recommended: "no",
        lessor_logo: "https://www.img.com/234567897654",
        lessor_ID: "LESSOR_87654323456",
        lessor_type: "bank",
        lessor_contact: {
          name: { en: "Mashal", ar: "مشعل" },
          phone: "+97199887766554",
          email: "kjh@gmail.com",
        },
      },
      progress_measure: "70",
      is_draft: "yes",
      dealer_details: {
        dealer_id: "dealer_65432345678",
        dealer_name: {
          en: "National Motor Distributors",
          ar: "الموزعون الوطنيون للمحركات",
        },
        dealer_logo: "https://www.img.com/234567897654",
        dealer_contact: {
          name: { en: "Yazan", ar: "يزن" },
          phone: "+97199887766554",
          email: "dealer@gmail.com",
        },
      },
      assigned_to_dealer_agent: "dealer_AGENTID_765432345",
      assigned_to_lessor_agent: "lessor_AGENTID_765432345",
    },
  },
  {
    application_id: {
      application_id: "987654321",
      lead_name: "John Duo",
      lead_ID: "lead_234565432",
      current_state: {
        label: {
          en: "Application Created",
          ar: "تم إنشاء الطلب",
        },
        color: "#FFA500",
      },
      current_actor: "Dealer",
      created_date: "2023-12-31T08:00:00Z",
      last_updated_at: "2023-12-31T08:05:00Z",
      iqama_id: "123456789012",
      driving_license_number: "MH12 20211234567",
      phone_number: "+1234567890",
      email: "john.duo@example.com",
      is_verified: "yes",
      status: "active",
      car_details: {
        brand: "KIA",
        model: "K8",
        variant: "KIA K8 2023 3.5L GDI LX",
        price: {
          actual: "85,000",
          discount: "2500",
          final_price: "82500",
        },
        car_image: "https://www.img.com/234567654321",
        color: { en: "Carpet Red", ar: "سجادة باللون الأحمر" },
      },
      lessor_details: {
        lessor_name: {
          en: "Demo Bank",
          ar: "بنك تجريبي",
        },
        recommended: "no",
        lessor_logo: "https://www.img.com/234567897654",
        lessor_ID: "LESSOR_87654323456",
        lessor_type: "bank",
        lessor_contact: {
          name: { en: "Mashal", ar: "مشعل" },
          phone: "+97199887766554",
          email: "lessoremail@demolessor.com",
        },
      },
      progress_measure: "70",
      is_draft: "yes",
      dealer_details: {
        dealer_id: "dealer_65432345678",
        dealer_name: {
          en: "National Motor Distributors",
          ar: "الموزعون الوطنيون للمحركات",
        },
        dealer_logo: "https://www.img.com/234567897654",
        dealer_contact: {
          name: { en: "Yazan", ar: "يزن" },
          phone: "+97199887766554",
          email: "dealeremail@demodealer.com",
        },
      },
      assigned_to_dealer_agent: "dealer_AGENTID_765432345",
      assigned_to_lessor_agent: "lessor_AGENTID_765432345",
    },
  },
  {
    application_id: {
      application_id: "123456789",
      lead_name: "Alice Smith",
      lead_ID: "lead_234565432",
      current_state: {
        label: {
          en: "Bank Decision",
          ar: "قرار البنك",
        },
        color: "#FFA500",
      },
      current_actor: "Bank",
      created_date: "2023-12-30T09:00:00Z",
      last_updated_at: "2023-12-31T09:30:00Z",
      iqama_id: "987654321098",
      driving_license_number: "MH12 20211234567",
      phone_number: "+19876543210",
      email: "alicesmith123@gmail.com",
      is_verified: "yes",
      status: "active",
      car_details: {
        brand: "KIA",
        model: "K8",
        variant: "KIA K8 2023 3.5L GDI LX",
        price: {
          actual: "85,000",
          discount: "2500",
          final_price: "82500",
        },
        car_image: "https://www.img.com/234567654321",
        color: { en: "Carpet Red", ar: "سجادة باللون الأحمر" },
      },
      lessor_details: {
        lessor_name: {
          en: "Demo Bank",
          ar: "بنك تجريبي",
        },
        recommended: "no",
        lessor_logo: "https://www.img.com/234567897654",
        lessor_ID: "LESSOR_87654323456",
        lessor_type: "bank",
        lessor_contact: {
          name: { en: "Mashal", ar: "مشعل" },
          phone: "+97199887766554",
          email: "kjh@gmail.com",
        },
      },
      progress_measure: "70",
      is_draft: "yes",
      dealer_details: {
        dealer_id: "dealer_65432345678",
        dealer_name: {
          en: "National Motor Distributors",
          ar: "الموزعون الوطنيون للمحركات",
        },
        dealer_logo: "https://www.img.com/234567897654",
        dealer_contact: {
          name: { en: "Yazan", ar: "يزن" },
          phone: "+97199887766554",
          email: "dealer@gmail.com",
        },
      },
      assigned_to_dealer_agent: "dealer_AGENTID_765432345",
      assigned_to_lessor_agent: "lessor_AGENTID_765432345",
    },
  },
  {
    application_id: {
      application_id: "987654321",
      lead_name: "John Duo",
      lead_ID: "lead_234565432",
      current_state: {
        label: {
          en: "Application Created",
          ar: "تم إنشاء الطلب",
        },
        color: "#FFA500",
      },
      current_actor: "Dealer",
      created_date: "2023-12-31T08:00:00Z",
      last_updated_at: "2023-12-31T08:05:00Z",
      iqama_id: "123456789012",
      driving_license_number: "MH12 20211234567",
      phone_number: "+1234567890",
      email: "john.duo@example.com",
      is_verified: "yes",
      status: "active",
      car_details: {
        brand: "KIA",
        model: "K8",
        variant: "KIA K8 2023 3.5L GDI LX",
        price: {
          actual: "85,000",
          discount: "2500",
          final_price: "82500",
        },
        car_image: "https://www.img.com/234567654321",
        color: { en: "Carpet Red", ar: "سجادة باللون الأحمر" },
      },
      lessor_details: {
        lessor_name: {
          en: "Demo Bank",
          ar: "بنك تجريبي",
        },
        recommended: "no",
        lessor_logo: "https://www.img.com/234567897654",
        lessor_ID: "LESSOR_87654323456",
        lessor_type: "bank",
        lessor_contact: {
          name: { en: "Mashal", ar: "مشعل" },
          phone: "+97199887766554",
          email: "lessoremail@demolessor.com",
        },
      },
      progress_measure: "70",
      is_draft: "yes",
      dealer_details: {
        dealer_id: "dealer_65432345678",
        dealer_name: {
          en: "National Motor Distributors",
          ar: "الموزعون الوطنيون للمحركات",
        },
        dealer_logo: "https://www.img.com/234567897654",
        dealer_contact: {
          name: { en: "Yazan", ar: "يزن" },
          phone: "+97199887766554",
          email: "dealeremail@demodealer.com",
        },
      },
      assigned_to_dealer_agent: "dealer_AGENTID_765432345",
      assigned_to_lessor_agent: "lessor_AGENTID_765432345",
    },
  },
  {
    application_id: {
      application_id: "123456789",
      lead_name: "Alice Smith",
      lead_ID: "lead_234565432",
      current_state: {
        label: {
          en: "Bank Decision",
          ar: "قرار البنك",
        },
        color: "#FFA500",
      },
      current_actor: "Bank",
      created_date: "2023-12-30T09:00:00Z",
      last_updated_at: "2023-12-31T09:30:00Z",
      iqama_id: "987654321098",
      driving_license_number: "MH12 20211234567",
      phone_number: "+19876543210",
      email: "alicesmith123@gmail.com",
      is_verified: "yes",
      status: "active",
      car_details: {
        brand: "KIA",
        model: "K8",
        variant: "KIA K8 2023 3.5L GDI LX",
        price: {
          actual: "85,000",
          discount: "2500",
          final_price: "82500",
        },
        car_image: "https://www.img.com/234567654321",
        color: { en: "Carpet Red", ar: "سجادة باللون الأحمر" },
      },
      lessor_details: {
        lessor_name: {
          en: "Demo Bank",
          ar: "بنك تجريبي",
        },
        recommended: "no",
        lessor_logo: "https://www.img.com/234567897654",
        lessor_ID: "LESSOR_87654323456",
        lessor_type: "bank",
        lessor_contact: {
          name: { en: "Mashal", ar: "مشعل" },
          phone: "+97199887766554",
          email: "kjh@gmail.com",
        },
      },
      progress_measure: "70",
      is_draft: "yes",
      dealer_details: {
        dealer_id: "dealer_65432345678",
        dealer_name: {
          en: "National Motor Distributors",
          ar: "الموزعون الوطنيون للمحركات",
        },
        dealer_logo: "https://www.img.com/234567897654",
        dealer_contact: {
          name: { en: "Yazan", ar: "يزن" },
          phone: "+97199887766554",
          email: "dealer@gmail.com",
        },
      },
      assigned_to_dealer_agent: "dealer_AGENTID_765432345",
      assigned_to_lessor_agent: "lessor_AGENTID_765432345",
    },
  },
  {
    application_id: {
      application_id: "987654321",
      lead_name: "John Duo",
      lead_ID: "lead_234565432",
      current_state: {
        label: {
          en: "Application Created",
          ar: "تم إنشاء الطلب",
        },
        color: "#FFA500",
      },
      current_actor: "Dealer",
      created_date: "2023-12-31T08:00:00Z",
      last_updated_at: "2023-12-31T08:05:00Z",
      iqama_id: "123456789012",
      driving_license_number: "MH12 20211234567",
      phone_number: "+1234567890",
      email: "john.duo@example.com",
      is_verified: "yes",
      status: "active",
      car_details: {
        brand: "KIA",
        model: "K8",
        variant: "KIA K8 2023 3.5L GDI LX",
        price: {
          actual: "85,000",
          discount: "2500",
          final_price: "82500",
        },
        car_image: "https://www.img.com/234567654321",
        color: { en: "Carpet Red", ar: "سجادة باللون الأحمر" },
      },
      lessor_details: {
        lessor_name: {
          en: "Demo Bank",
          ar: "بنك تجريبي",
        },
        recommended: "no",
        lessor_logo: "https://www.img.com/234567897654",
        lessor_ID: "LESSOR_87654323456",
        lessor_type: "bank",
        lessor_contact: {
          name: { en: "Mashal", ar: "مشعل" },
          phone: "+97199887766554",
          email: "lessoremail@demolessor.com",
        },
      },
      progress_measure: "70",
      is_draft: "yes",
      dealer_details: {
        dealer_id: "dealer_65432345678",
        dealer_name: {
          en: "National Motor Distributors",
          ar: "الموزعون الوطنيون للمحركات",
        },
        dealer_logo: "https://www.img.com/234567897654",
        dealer_contact: {
          name: { en: "Yazan", ar: "يزن" },
          phone: "+97199887766554",
          email: "dealeremail@demodealer.com",
        },
      },
      assigned_to_dealer_agent: "dealer_AGENTID_765432345",
      assigned_to_lessor_agent: "lessor_AGENTID_765432345",
    },
  },
];

export const newleads: NewDetailedLead[] = [
  {
    personal_details: {
      name: "John Duo",
      phone_number: "+1234567890",
      email: "john.duo@example.com",
      dob: "23-08-1897",
      alternate_phone: "+1234567890",
      any_other_loans: "yes",
      monthly_expense: "4000",
      marital_status: "single",
    },
    professional_details: {
      employement_type: "employed",
      monthly_salary: "7500",
      total_experience: "15",
      current_employer: "BHUPA",
    },
    eductation_details: {
      education_completed: "bachelors",
      major: "computer science",
    },
    vehicle_details: {
      brand: "KIA",
      model: "Sonet",
      variant: "LX S 4",
      color: "red",
      addons: "",
      vehicle_type: "new",
    },
    lease_offer_details: {
      total_amount: "65000",
      interest: "6",
      installments: "48",
      monthly_EMI: "2400",
      credit_score: "546",
    },
    uploaded_docs: {
      driving_license: "https://www.img.com/8765678",
      iqama_doc: "https://www.img.com/8765678",
      photo: "https://www.img.com/8765678",
      salary_certificate: "https://www.img.com/8765678",
      income_statement: "https://www.img.com/8765678",
    },
    booking_payment_details: {
      booking_amount: "5000",
      amount_paid: "5000",
      amount_paid_by: "customer",
      payment_mode: "cash",
      payment_date: "2023-12-31T08:00:00Z",
    },
    history_timeline: {
      states: {
        "1": {
          name: {
            en: "Application Initiated",
            ar: "تم تشغيل التطبيق",
          },
          status: "completed",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "start",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "2": {
          name: {
            en: "Bank Verifications",
            ar: "التحققات البنكية",
          },
          status: "completed",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "3": {
          count: "8",
          name: {
            en: "Document Upload by Customer",
            ar: "التحقق من الوثائق",
          },
          status: "current",
          actor: "customer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "4": {
          name: {
            en: "Dealer Acknowledgement",
            ar: "إقرار الموزع",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "5": {
          name: {
            en: "Loan Approved",
            ar: "تمت الموافقة على القرض",
          },
          status: "upcoming",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "6": {
          name: {
            en: "Vehicle Delivery",
            ar: "تسليم المركبة",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "7": {
          name: {
            en: "Loan Disbursed",
            ar: "تم رفض القرض",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "close-won",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
      },
    },
    actions: {
      "1": {
        en: "Upload Documents",
        ar: "Upload Documents",
      },
      actor: "customer",
      fields: {
        "1": {
          name: "Salary Certificate",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "1",
        },
        "2": {
          name: "Income Proof",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "3",
        },
        "3": {
          name: "Passport Photo",
          type: "mm/JPEG",
          max_size: "1MB",
          accepted_count: "1",
        },
      },
    },
    nba: {
      en: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
      ar: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
    },
  },
  {
    personal_details: {
      name: "John Duo",
      phone_number: "+1234567890",
      email: "john.duo@example.com",
      dob: "23-08-1897",
      alternate_phone: "+1234567890",
      any_other_loans: "yes",
      monthly_expense: "4000",
      marital_status: "single",
    },
    professional_details: {
      employement_type: "employed",
      monthly_salary: "7500",
      total_experience: "15",
      current_employer: "BHUPA",
    },
    eductation_details: {
      education_completed: "bachelors",
      major: "computer science",
    },
    vehicle_details: {
      brand: "KIA",
      model: "Sonet",
      variant: "LX S 4",
      color: "red",
      addons: "",
      vehicle_type: "new",
    },
    lease_offer_details: {
      total_amount: "65000",
      interest: "6",
      installments: "48",
      monthly_EMI: "2400",
      credit_score: "546",
    },
    uploaded_docs: {
      driving_license: "https://www.img.com/8765678",
      iqama_doc: "https://www.img.com/8765678",
      photo: "https://www.img.com/8765678",
      salary_certificate: "https://www.img.com/8765678",
      income_statement: "https://www.img.com/8765678",
    },
    booking_payment_details: {
      booking_amount: "5000",
      amount_paid: "5000",
      amount_paid_by: "customer",
      payment_mode: "cash",
      payment_date: "2023-12-31T08:00:00Z",
    },
    history_timeline: {
      states: {
        "1": {
          name: {
            en: "Application Initiated",
            ar: "تم تشغيل التطبيق",
          },
          status: "completed",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "start",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "2": {
          name: {
            en: "Bank Verifications",
            ar: "التحققات البنكية",
          },
          status: "completed",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "3": {
          count: "8",
          name: {
            en: "Document Upload by Customer",
            ar: "التحقق من الوثائق",
          },
          status: "current",
          actor: "customer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "4": {
          name: {
            en: "Dealer Acknowledgement",
            ar: "إقرار الموزع",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "5": {
          name: {
            en: "Loan Approved",
            ar: "تمت الموافقة على القرض",
          },
          status: "upcoming",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "6": {
          name: {
            en: "Vehicle Delivery",
            ar: "تسليم المركبة",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "7": {
          name: {
            en: "Loan Disbursed",
            ar: "تم رفض القرض",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "close-won",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
      },
    },
    actions: {
      "1": {
        en: "Upload Documents",
        ar: "Upload Documents",
      },
      actor: "customer",
      fields: {
        "1": {
          name: "Salary Certificate",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "1",
        },
        "2": {
          name: "Income Proof",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "3",
        },
        "3": {
          name: "Passport Photo",
          type: "mm/JPEG",
          max_size: "1MB",
          accepted_count: "1",
        },
      },
    },
    nba: {
      en: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
      ar: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
    },
  },
  {
    personal_details: {
      name: "John Duo",
      phone_number: "+1234567890",
      email: "john.duo@example.com",
      dob: "23-08-1897",
      alternate_phone: "+1234567890",
      any_other_loans: "yes",
      monthly_expense: "4000",
      marital_status: "single",
    },
    professional_details: {
      employement_type: "employed",
      monthly_salary: "7500",
      total_experience: "15",
      current_employer: "BHUPA",
    },
    eductation_details: {
      education_completed: "bachelors",
      major: "computer science",
    },
    vehicle_details: {
      brand: "KIA",
      model: "Sonet",
      variant: "LX S 4",
      color: "red",
      addons: "",
      vehicle_type: "new",
    },
    lease_offer_details: {
      total_amount: "65000",
      interest: "6",
      installments: "48",
      monthly_EMI: "2400",
      credit_score: "546",
    },
    uploaded_docs: {
      driving_license: "https://www.img.com/8765678",
      iqama_doc: "https://www.img.com/8765678",
      photo: "https://www.img.com/8765678",
      salary_certificate: "https://www.img.com/8765678",
      income_statement: "https://www.img.com/8765678",
    },
    booking_payment_details: {
      booking_amount: "5000",
      amount_paid: "5000",
      amount_paid_by: "customer",
      payment_mode: "cash",
      payment_date: "2023-12-31T08:00:00Z",
    },
    history_timeline: {
      states: {
        "1": {
          name: {
            en: "Application Initiated",
            ar: "تم تشغيل التطبيق",
          },
          status: "completed",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "start",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "2": {
          name: {
            en: "Bank Verifications",
            ar: "التحققات البنكية",
          },
          status: "completed",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "3": {
          count: "8",
          name: {
            en: "Document Upload by Customer",
            ar: "التحقق من الوثائق",
          },
          status: "current",
          actor: "customer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "4": {
          name: {
            en: "Dealer Acknowledgement",
            ar: "إقرار الموزع",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "5": {
          name: {
            en: "Loan Approved",
            ar: "تمت الموافقة على القرض",
          },
          status: "upcoming",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "6": {
          name: {
            en: "Vehicle Delivery",
            ar: "تسليم المركبة",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "7": {
          name: {
            en: "Loan Disbursed",
            ar: "تم رفض القرض",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "close-won",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
      },
    },
    actions: {
      "1": {
        en: "Upload Documents",
        ar: "Upload Documents",
      },
      actor: "customer",
      fields: {
        "1": {
          name: "Salary Certificate",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "1",
        },
        "2": {
          name: "Income Proof",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "3",
        },
        "3": {
          name: "Passport Photo",
          type: "mm/JPEG",
          max_size: "1MB",
          accepted_count: "1",
        },
      },
    },
    nba: {
      en: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
      ar: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
    },
  },
  {
    personal_details: {
      name: "John Duo",
      phone_number: "+1234567890",
      email: "john.duo@example.com",
      dob: "23-08-1897",
      alternate_phone: "+1234567890",
      any_other_loans: "yes",
      monthly_expense: "4000",
      marital_status: "single",
    },
    professional_details: {
      employement_type: "employed",
      monthly_salary: "7500",
      total_experience: "15",
      current_employer: "BHUPA",
    },
    eductation_details: {
      education_completed: "bachelors",
      major: "computer science",
    },
    vehicle_details: {
      brand: "KIA",
      model: "Sonet",
      variant: "LX S 4",
      color: "red",
      addons: "",
      vehicle_type: "new",
    },
    lease_offer_details: {
      total_amount: "65000",
      interest: "6",
      installments: "48",
      monthly_EMI: "2400",
      credit_score: "546",
    },
    uploaded_docs: {
      driving_license: "https://www.img.com/8765678",
      iqama_doc: "https://www.img.com/8765678",
      photo: "https://www.img.com/8765678",
      salary_certificate: "https://www.img.com/8765678",
      income_statement: "https://www.img.com/8765678",
    },
    booking_payment_details: {
      booking_amount: "5000",
      amount_paid: "5000",
      amount_paid_by: "customer",
      payment_mode: "cash",
      payment_date: "2023-12-31T08:00:00Z",
    },
    history_timeline: {
      states: {
        "1": {
          name: {
            en: "Application Initiated",
            ar: "تم تشغيل التطبيق",
          },
          status: "completed",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "start",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "2": {
          name: {
            en: "Bank Verifications",
            ar: "التحققات البنكية",
          },
          status: "completed",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "3": {
          count: "8",
          name: {
            en: "Document Upload by Customer",
            ar: "التحقق من الوثائق",
          },
          status: "current",
          actor: "customer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "4": {
          name: {
            en: "Dealer Acknowledgement",
            ar: "إقرار الموزع",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "5": {
          name: {
            en: "Loan Approved",
            ar: "تمت الموافقة على القرض",
          },
          status: "upcoming",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "6": {
          name: {
            en: "Vehicle Delivery",
            ar: "تسليم المركبة",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "7": {
          name: {
            en: "Loan Disbursed",
            ar: "تم رفض القرض",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "close-won",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
      },
    },
    actions: {
      "1": {
        en: "Upload Documents",
        ar: "Upload Documents",
      },
      actor: "customer",
      fields: {
        "1": {
          name: "Salary Certificate",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "1",
        },
        "2": {
          name: "Income Proof",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "3",
        },
        "3": {
          name: "Passport Photo",
          type: "mm/JPEG",
          max_size: "1MB",
          accepted_count: "1",
        },
      },
    },
    nba: {
      en: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
      ar: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
    },
  },
  {
    personal_details: {
      name: "John Duo",
      phone_number: "+1234567890",
      email: "john.duo@example.com",
      dob: "23-08-1897",
      alternate_phone: "+1234567890",
      any_other_loans: "yes",
      monthly_expense: "4000",
      marital_status: "single",
    },
    professional_details: {
      employement_type: "employed",
      monthly_salary: "7500",
      total_experience: "15",
      current_employer: "BHUPA",
    },
    eductation_details: {
      education_completed: "bachelors",
      major: "computer science",
    },
    vehicle_details: {
      brand: "KIA",
      model: "Sonet",
      variant: "LX S 4",
      color: "red",
      addons: "",
      vehicle_type: "new",
    },
    lease_offer_details: {
      total_amount: "65000",
      interest: "6",
      installments: "48",
      monthly_EMI: "2400",
      credit_score: "546",
    },
    uploaded_docs: {
      driving_license: "https://www.img.com/8765678",
      iqama_doc: "https://www.img.com/8765678",
      photo: "https://www.img.com/8765678",
      salary_certificate: "https://www.img.com/8765678",
      income_statement: "https://www.img.com/8765678",
    },
    booking_payment_details: {
      booking_amount: "5000",
      amount_paid: "5000",
      amount_paid_by: "customer",
      payment_mode: "cash",
      payment_date: "2023-12-31T08:00:00Z",
    },
    history_timeline: {
      states: {
        "1": {
          name: {
            en: "Application Initiated",
            ar: "تم تشغيل التطبيق",
          },
          status: "completed",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "start",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "2": {
          name: {
            en: "Bank Verifications",
            ar: "التحققات البنكية",
          },
          status: "completed",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "3": {
          count: "8",
          name: {
            en: "Document Upload by Customer",
            ar: "التحقق من الوثائق",
          },
          status: "current",
          actor: "customer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "4": {
          name: {
            en: "Dealer Acknowledgement",
            ar: "إقرار الموزع",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "5": {
          name: {
            en: "Loan Approved",
            ar: "تمت الموافقة على القرض",
          },
          status: "upcoming",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "6": {
          name: {
            en: "Vehicle Delivery",
            ar: "تسليم المركبة",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "7": {
          name: {
            en: "Loan Disbursed",
            ar: "تم رفض القرض",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "close-won",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
      },
    },
    actions: {
      "1": {
        en: "Upload Documents",
        ar: "Upload Documents",
      },
      actor: "customer",
      fields: {
        "1": {
          name: "Salary Certificate",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "1",
        },
        "2": {
          name: "Income Proof",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "3",
        },
        "3": {
          name: "Passport Photo",
          type: "mm/JPEG",
          max_size: "1MB",
          accepted_count: "1",
        },
      },
    },
    nba: {
      en: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
      ar: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
    },
  },
  {
    personal_details: {
      name: "John Duo",
      phone_number: "+1234567890",
      email: "john.duo@example.com",
      dob: "23-08-1897",
      alternate_phone: "+1234567890",
      any_other_loans: "yes",
      monthly_expense: "4000",
      marital_status: "single",
    },
    professional_details: {
      employement_type: "employed",
      monthly_salary: "7500",
      total_experience: "15",
      current_employer: "BHUPA",
    },
    eductation_details: {
      education_completed: "bachelors",
      major: "computer science",
    },
    vehicle_details: {
      brand: "KIA",
      model: "Sonet",
      variant: "LX S 4",
      color: "red",
      addons: "",
      vehicle_type: "new",
    },
    lease_offer_details: {
      total_amount: "65000",
      interest: "6",
      installments: "48",
      monthly_EMI: "2400",
      credit_score: "546",
    },
    uploaded_docs: {
      driving_license: "https://www.img.com/8765678",
      iqama_doc: "https://www.img.com/8765678",
      photo: "https://www.img.com/8765678",
      salary_certificate: "https://www.img.com/8765678",
      income_statement: "https://www.img.com/8765678",
    },
    booking_payment_details: {
      booking_amount: "5000",
      amount_paid: "5000",
      amount_paid_by: "customer",
      payment_mode: "cash",
      payment_date: "2023-12-31T08:00:00Z",
    },
    history_timeline: {
      states: {
        "1": {
          name: {
            en: "Application Initiated",
            ar: "تم تشغيل التطبيق",
          },
          status: "completed",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "start",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "2": {
          name: {
            en: "Bank Verifications",
            ar: "التحققات البنكية",
          },
          status: "completed",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "3": {
          count: "8",
          name: {
            en: "Document Upload by Customer",
            ar: "التحقق من الوثائق",
          },
          status: "current",
          actor: "customer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "4": {
          name: {
            en: "Dealer Acknowledgement",
            ar: "إقرار الموزع",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "5": {
          name: {
            en: "Loan Approved",
            ar: "تمت الموافقة على القرض",
          },
          status: "upcoming",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "6": {
          name: {
            en: "Vehicle Delivery",
            ar: "تسليم المركبة",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "7": {
          name: {
            en: "Loan Disbursed",
            ar: "تم رفض القرض",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "close-won",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
      },
    },
    actions: {
      "1": {
        en: "Upload Documents",
        ar: "Upload Documents",
      },
      actor: "customer",
      fields: {
        "1": {
          name: "Salary Certificate",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "1",
        },
        "2": {
          name: "Income Proof",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "3",
        },
        "3": {
          name: "Passport Photo",
          type: "mm/JPEG",
          max_size: "1MB",
          accepted_count: "1",
        },
      },
    },
    nba: {
      en: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
      ar: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
    },
  },
  {
    personal_details: {
      name: "John Duo",
      phone_number: "+1234567890",
      email: "john.duo@example.com",
      dob: "23-08-1897",
      alternate_phone: "+1234567890",
      any_other_loans: "yes",
      monthly_expense: "4000",
      marital_status: "single",
    },
    professional_details: {
      employement_type: "employed",
      monthly_salary: "7500",
      total_experience: "15",
      current_employer: "BHUPA",
    },
    eductation_details: {
      education_completed: "bachelors",
      major: "computer science",
    },
    vehicle_details: {
      brand: "KIA",
      model: "Sonet",
      variant: "LX S 4",
      color: "red",
      addons: "",
      vehicle_type: "new",
    },
    lease_offer_details: {
      total_amount: "65000",
      interest: "6",
      installments: "48",
      monthly_EMI: "2400",
      credit_score: "546",
    },
    uploaded_docs: {
      driving_license: "https://www.img.com/8765678",
      iqama_doc: "https://www.img.com/8765678",
      photo: "https://www.img.com/8765678",
      salary_certificate: "https://www.img.com/8765678",
      income_statement: "https://www.img.com/8765678",
    },
    booking_payment_details: {
      booking_amount: "5000",
      amount_paid: "5000",
      amount_paid_by: "customer",
      payment_mode: "cash",
      payment_date: "2023-12-31T08:00:00Z",
    },
    history_timeline: {
      states: {
        "1": {
          name: {
            en: "Application Initiated",
            ar: "تم تشغيل التطبيق",
          },
          status: "completed",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "start",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "2": {
          name: {
            en: "Bank Verifications",
            ar: "التحققات البنكية",
          },
          status: "completed",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "3": {
          count: "8",
          name: {
            en: "Document Upload by Customer",
            ar: "التحقق من الوثائق",
          },
          status: "current",
          actor: "customer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "4": {
          name: {
            en: "Dealer Acknowledgement",
            ar: "إقرار الموزع",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "5": {
          name: {
            en: "Loan Approved",
            ar: "تمت الموافقة على القرض",
          },
          status: "upcoming",
          actor: "bank",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "6": {
          name: {
            en: "Vehicle Delivery",
            ar: "تسليم المركبة",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "intermediate",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
        "7": {
          name: {
            en: "Loan Disbursed",
            ar: "تم رفض القرض",
          },
          status: "upcoming",
          actor: "dealer",
          completed_by: "dealer_ID_764326543",
          completed_at: "dealer_ID_764326543",
          updated_by: "internal_ID_764326543",
          updated_at: "dealer_ID_764326543",
          state_type: "close-won",
          view_permission_actors: "dealer, bank, customer",
          edit_permission_actors: "dealer, bank, customer",
        },
      },
    },
    actions: {
      "1": {
        en: "Upload Documents",
        ar: "Upload Documents",
      },
      actor: "customer",
      fields: {
        "1": {
          name: "Salary Certificate",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "1",
        },
        "2": {
          name: "Income Proof",
          type: "mm/pdf",
          max_size: "1MB",
          accepted_count: "3",
        },
        "3": {
          name: "Passport Photo",
          type: "mm/JPEG",
          max_size: "1MB",
          accepted_count: "1",
        },
      },
    },
    nba: {
      en: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
      ar: "Awaiting for customer to upload all the necessery documentes, followup today to fastrack",
    },
  },
];
